nameOverride: "developer-hub-prereqs"

namespace: rhdh

vault:
  namespace: vault
  name: vault

operator:
  channel: fast-1.9
  startingCSV: rhdh-operator.v1.9.2
  installPlanApproval: Automatic

argocd:
  enabled: true
  syncwave: "-1"
