apiVersion: v2
name: trusted-profile-analyzer
description: Trusted Profile Analyzer (TPA/Trustify) umbrella chart
type: application
version: 0.1.0

dependencies:
  - name: tpa-prerequisites
    version: 0.1.0
    repository: file://charts/tpa-prerequisites
  - name: redhat-trusted-profile-analyzer
    version: "1.1.1"
    repository: "https://charts.openshift.io/"
